package net

// Generated by portassignments.py

//
// operator station
//
// Gpsd messages from vehicle gpsdrt to the operator.
const OperatorGpsdListen = 6001

// Bidi listener for trajectories and trajectory-applied messages.
const OperatorTrajectoryListen = 6002

// Gpsd messages from the gpsd listener to trajectory planner. localhost
const OperatorGpsdTrajectory = 7001

// Overlay messages from decoder, trajectory planner, and gpsd listener to operator (display).
const OperatorOverlayListen = 2221

// Decoded video messages from decoder to operator (display).
const OperatorVideoListen = 8888

//
// vehicle
//
// Trajectory requests from trajectory dialer to trajectory execution; trajectory-applied messages from trajectory execution to trajectory dialer for forwarding. localhost
const VehicleTrajectoryRequestApplication = 7000

