package net

// Generated by portassignments.py

//
// operator station
//
// Gpsd messages from vehicle gpsdrt to the operator.
const OperatorGpsdListen = 6001

// Trajectory-applied messages from vehicle trajectory execution to operator.
const OperatorTrajectoryListen = 6002

// Gpsd messages from the gpsd listener to display.
const OperatorGpsdDisplay = 7000

// Gpsd messages from the gpsd listener to trajectory planner.
const OperatorGpsdTrajectory = 7001

// Trajectory messages from trajectory planner to trajectory listener for forwarding.
const OperatorTrajectoryRequest = 7002

// Trajectory-applied messages from trajectory listener to display.
const OperatorTrajectoryApplication = 7003

// Overlay messages from decoder to operator (display).
const OperatorOverlayListen = 7777

// Decoded video messages from decoder to operator (display).
const OperatorVideoListen = 8888

//
// vehicle
//
// Trajectory requests from trajectory dialer to trajectory execution
const VehicleTrajectoryRequest = 7000

// trajectory-applied messages from trajectory execution to trajectory dialer for forwarding.
const VehicleTrajectoryApplication = 7001

