package net

// Generated by portassignments.py

//
// operator station, external
//
// Listen on this port for GPSD messages from vehicle
const OperatorGPSDListener = 6001

// Trajectory listener end of bidirectional dialer --> listener
const OperatorTrajectoryListener = 6002

//
// operator station, localhost
//
// Send GPSD messages from the GPSD listener to display
const OperatorGPSDDisplay = 7000

// Send GPSD messages from the GPSD listener to trajectory planner
const OperatorGPSDTrajectory = 7001

// Send trajectory messages from trajectory planner to trajectory listener
const OperatorTrajectoryRequest = 7002

// Send trajectory-application reports from trajectory listener to display
const OperatorTrajectoryApplication = 7003

//
// vehicle, external
//
//
// vehicle, localhost
//
// Send trajectory requests from trajectory dialer to trajectory execution
const VehicleTrajectoryRequest = 7000

// Send trajectory-applied messages from trajectory execution to trajectory dialer for forwarding.
const VehicleTrajectoryApplication = 7001

