# Generate language-appropriate files for port assignments.
import collections
import sys

Assignment = collections.namedtuple('PortAssignment',
                                    ['name', 'number', 'comment'])

all_assignments = [
("operator station, external",
 [Assignment(
     "OperatorGPSDListener", 6001,
     "Listen on this port for GPSD messages from vehicle"),
  Assignment(
      "OperatorTrajectoryListener", 6002,
      "Trajectory listener end of bidirectional dialer --> listener"),
  ]),

("operator station, localhost",
 [Assignment(
     "OperatorGPSDDisplay", 7000,
     "Send GPSD messages from the GPSD listener to display"),
  Assignment(
      "OperatorGPSDTrajectory", 7001,
      "Send GPSD messages from the GPSD listener to trajectory planner"),
  Assignment(
      "OperatorTrajectoryRequest", 7002,
      "Send trajectory messages from trajectory planner to trajectory listener"),
  Assignment(
      "OperatorTrajectoryApplication", 7003,
      "Send trajectory-application reports from trajectory listener to display"),
  ]),

    
("vehicle, external",
 [
 ]),

("vehicle, localhost",
 [Assignment(
     "VehicleTrajectoryRequest", 7000,
     "Send trajectory requests from trajectory dialer to "
     "trajectory execution"),
  
  Assignment(
      "VehicleTrajectoryApplication", 7001,
      "Send trajectory-applied messages from trajectory execution "
      "to trajectory dialer for forwarding."),
  ]),
]

def main():
    with open("port.go", "w") as f:
        print("package net\n", file=f)
        print("// Generated by %s" % (sys.argv[0],), file=f)
        print("", file=f)
        for (tag, assignments) in all_assignments:
            print("//\n// %s\n//" % (tag,), file=f)
            for a in assignments:
                print("// %s" % (a.comment,), file=f)
                print("const %s = %d" % (a.name, a.number), file=f)
                print("", file=f)

    with open("port.py", "w") as f:
        print("# Generated by %s" % (sys.argv[0],), file=f)
        print("", file=f)
        for (tag, assignments) in all_assignments:
            print("\n# %s\n#" % (tag,), file=f)
            for a in assignments:
                print("# %s" % (a.comment,), file=f)
                print("%s = %d" % (a.name, a.number), file=f)
                print("", file=f)

    with open("port.h", "w") as f:
        print("#ifndef REMNAV_NET_PORTS_H_", file=f)
        print("#define  REMNAV_NET_PORTS_H_", file=f)
        print("#include <stdint.h>", file=f)
        print("// Generated by %s." % (sys.argv[0],), file=f)
        print("", file=f)
        for (tag, assignments) in all_assignments:
            print("\n// %s\n//" % (tag,), file=f)
            for a in assignments:
                print("// %s" % (a.comment,), file=f)
                print("const int32_t f%s = %d;" % (a.name, a.number), file=f)
                print("", file=f)
        print("#endif  // REMNAV_NET_PORTS_H_", file=f)

if __name__ == "__main__":
    main()
    
